"""remove_default_and_soft_delete_kb

Revision ID: fd19ed0b208e
Revises: 1c4d9bcb86c7
Create Date: 2026-07-11 20:07:04.242618
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'fd19ed0b208e'
down_revision: Union[str, Sequence[str], None] = '1c4d9bcb86c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_kb_usage_default', table_name='knowledge_base')
    op.drop_index('uq_kb_active_default_usage', table_name='knowledge_base')
    op.drop_index('idx_kb_usage_active', table_name='knowledge_base')
    op.drop_column('knowledge_base', 'active_default_usage')
    op.drop_column('knowledge_base', 'is_default')
    op.drop_column('knowledge_base', 'is_deleted')
    op.create_index('idx_kb_usage', 'knowledge_base', ['usage_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_kb_usage', table_name='knowledge_base')
    op.add_column('knowledge_base', sa.Column('is_deleted', sa.Boolean(), server_default=sa.text("'0'"), nullable=False))
    op.add_column('knowledge_base', sa.Column('is_default', sa.Boolean(), server_default=sa.text("'0'"), nullable=False))
    op.add_column('knowledge_base', sa.Column('active_default_usage', sa.String(32), sa.Computed('CASE WHEN is_default = 1 AND is_deleted = 0 THEN usage_type ELSE NULL END', persisted=True), nullable=True))
    op.create_index('uq_kb_active_default_usage', 'knowledge_base', ['active_default_usage'], unique=True)
    op.create_index('idx_kb_usage_default', 'knowledge_base', ['usage_type', 'is_default', 'is_deleted'], unique=False)
    op.create_index('idx_kb_usage_active', 'knowledge_base', ['usage_type', 'is_deleted'], unique=False)
    # ### end Alembic commands ###
